### ISSUE TITLE
Documentation page not found

### ISSUE THREAD

**Issue by reneandritsch** [RxLaboratory/DuME#252]
**Describe the bug**
The weblink cannot connect to the server ;-)

https://dume-docs.rainboxlab.org

Thanks for having a look at it.

![Bildschirmfoto 2021-07-21 um 13 40 45](https://user-images.githubusercontent.com/38455050/126483074-a5ef7527-cb8f-42c3-92cb-1334fe66efc8.png)

**Comment by Nico-Duduf** [comment]
Hi René,

It's been moved to http://dume.rxlab.guide
But there should be an automatic redirection, I'll have a look. Thanks!

**Comment by Nico-Duduf** [comment]
Hum it's because of the "s" in https, because it was a secure connexion, it seems I can't easily redirect it...

**Comment by reneandritsch** [comment]
Thanks for fixing it! Have a great summer. I hope you have some time off, too!
