### ISSUE TITLE
"Invalid data found when processing input" Console Log FFMPEG

### ISSUE THREAD

**Issue by wasabii-boy** [RxLaboratory/DuME#260]
Hello,

Quand j’essaye de lancer un rendu depuis after effect ou en glissant un projet AE, j’ai une erreur FFMPEG "Invalid data found when processing input" pourtant j’ai essayé de tout réinstaller même FFMPEG mais rien y fait. 

1. AE ou Projet dans DuME
2. Erreur FFMPEG
3. Pas de rendu

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/64318547/154624052-b0e8cb7f-ec6f-4e99-a7a0-f9bfdee64a89.png">

 - Version of the OS:  MacOS 12.2
 - Version of DuME:  V.0.3.0

**Comment by Nico-Duduf** [comment]
ce message est "normal" quand on met un projet after (il faudrait que je le vire cela dit), mais il se passe quoi quand tu lances le rendu ? Une erreur, un plantage, quelque chose ?

**Comment by wasabii-boy** [comment]
Il tente de lancer le rendu, mais rien ne se passe finalement, pas de fichier ni de message d'erreur. C'est un lancement à vide.

**Comment by Nico-Duduf** [comment]
Et ça ne fonctionne sur aucun projet ? Il y a quoi dans la console "After Effects" ?

**Comment by wasabii-boy** [comment]
Non aucun malheureusement,
<img width="1326" alt="Capture d’écran 2022-03-05 à 17 14 42" src="https://user-images.githubusercontent.com/64318547/156891428-20056246-545a-402e-a973-86b7f315ad4a.png">

**Comment by Nico-Duduf** [comment]
C'est de plus en plus bizarre cette histoire...
Est ce que tu pourrais : 
1. Faire une capture vidéo de tout ce que tu fais, depuis after effects jusqu'au lancement du rendu ; voir si il y a un truc spécifique
2. m'envoyer un projet after tel qu'il est ajouté dans DuME ? (celui qui correspond au chemin en haut du panneau Input) ?

**Comment by wasabii-boy** [comment]
Voici la vidéo et le projet after, j’espère que ça t’aidera.

https://user-images.githubusercontent.com/64318547/156896420-a80bed7d-9b3e-4c43-b855-2ee0e06ecd5b.mp4

[Minimal Sunset.aep.zip](https://github.com/RxLaboratory/DuME/files/8191256/Minimal.Sunset.aep.zip)

**Comment by AllenC2** [comment]
then... anything?

**Comment by wasabii-boy** [comment]
Hello, apparemment ça été fix avec AE 2023, je n'ai plus le problème haha
